dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - python -m pip install -U pip
  - python -m pip install -e .[dev]
  - python -m pip install flake8 pytest pytest-cov codecov
  
# command to run tests
script:
  - pytest lime
  - flake8 lime
  
# Push the results back to codecov  
after_success:
  - codecov  
